# -*- coding: utf-8 -*-
"""Gas detection using thermal cameras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_dDdiv6axWdN0KvZVRoRC5xlr-faSgT0
"""

import numpy as np
import cv2
print("Here please add the path of a previously saved image of how the view you are monitoring normally looks")
normal_img_path = input('Normal Image Path - ') #Here please add the path of a previously saved image of how the view you are monitoring normally looks
normal_img = cv2.imread(normal_img_path)
normal_img_mean = np.mean(normal_img)
normal_img_std = np.std(normal_img)
snd_normal = stats.norm(normal_img_mean, normal_img_std)

print("Here please add the path of a previously saved image of how the view you are monitoring filled with gas")
gas_img_path = input('Gas image path - ') #Here please add the path of a previously saved image of how the view you are monitoring filled with gas
gas_img = cv2.imread(gas_img_path)
gas_img_mean = np.mean(gas_img)
gas_img_std = np.std(gas_img)
snd_gas = stats.norm(gas_img_mean,gas_img_std)

x = np.linspace(normal_img_mean, gas_img_mean, 1000)
min_val =np.argmin(np.abs( snd_normal.pdf(x) - snd_gas.pdf(x) ))
boundary = x[min_val]